/* eslint-disable import/prefer-default-export */
export const GET_USER_CHARACTERISITCS = 'GET_USER_CHARACTERISITICS'
export const ADD_TOXIC = 'ADD_TOXIC'
export const MINUS_TOXIC = 'MINUS_TOXIC'
export const ADD_FRIENDLY = 'ADD_FRIENDLY'
export const MINUS_FRIENDLY = 'MINUS_FRIENDLY'
export const ADD_TEAM_PLAY = 'ADD_TEAM_PLAY'
export const MINUS_TEAM_PLAY = 'MINUS_TEAM_PLAY'
export const ADD_STRATEGY = 'ADD_STRATEGY'
export const MINUS_STRATEGY = 'MINUS_STRATEGY'
export const ADD_LEADER = 'ADD_LEADER'
export const MINUS_LEADER = 'MINUS_LEADER'
